name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker image build -t m3allimm4a4/wellness-with-jana-back -t m3allimm4a4/wellness-with-jana-back:${{ github.run_number }} -f ./docker/back.dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker image push m3allimm4a4/wellness-with-jana-back
          docker image push m3allimm4a4/wellness-with-jana-back:${{ github.run_number }}
